name: interactive_journal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: 2.3.5
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.png
    - assets/sunny_window.png
    - assets/rainy_window.png
    - assets/overcast_window.png
    - assets/night_window.png
    - assets/rainbow_window.png
    - assets/clouds.png
    - assets/menu_banner.png
    - assets/mood_background.png
    - assets/help_boxes.png
    - assets/about_footer.png
    - assets/app_logo.png
    - assets/prompts_box.png
    - assets/mood_box.png
    - assets/avatar1.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/avatar4.png
    - assets/avatar5.png
    - assets/avatar_load.png

flutter_native_splash:
  color: "#fbf1e0"
  image: assets/splash_logo.png
  android: true
  ios: true
