name: interactive_journal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: 2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.png
    - assets/sunny_window.png
    - assets/rainy_window.png
    - assets/clouds.png

flutter_native_splash:
  color: "#fbf1e0"
  image: assets/splash_logo.png
  android: true
  ios: true
